user:
  avatarBaseSrc: E:/user_avatar
  avatarFaultName: default.png
product:
  pagesize: 8
  pictureBaseSrc: E:/ppicture
  pictureSuffix: .jpg

spring:
  application:
    name: shopView
#  redis:
#    port: 6379
#    host: 192.168.129.128
#    nacos注册信息
  cloud:
    nacos:
      ##注册
      discovery:
        server-addr: 192.168.129.128:8848

  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/project
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/static , file:E:/ppicture, file:E:/user_avatar
#    http://192.168.129.128/ppicture/,http://192.168.129.128/userAvatar/
  thymeleaf:
    prefix: classpath:/templates/


server:
  port: 80
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000